<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>

        const promise = Promise.resolve()
            .then(() => {
                return promise
            })

        promise.catch(console.error)

    </script>

    运行结果：

    TypeError: Chaining cycle detected for promise #<Promise>
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
        at Function.Module.runMain (module.js:667:11)
        at startup (bootstrap_node.js:187:16)
        at bootstrap_node.js:607:3
        
        解释：.then 或 .catch 返回的值不能是 promise 本身，否则会造成死循环。类似于：
        process.nextTick(function tick () {
          console.log('tick')
          process.nextTick(tick)
        })

</body>

</html>
